server.max-http-header-size: 48000
spring:
  application:
    id: "100"
    name: ocr-implementation-service
    entity-id: UD
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: true
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob.non_contextual_creation: true
#    database: default
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    username: postgres
#    password: waplak
#    url: jdbc:postgresql://localhost:5432/account_origination_db
#    driverClassName: org.postgresql.Driver
#  liquibase:
#    change-log: file:db/liquibase/liquibase-changelog.xml
#    enabled: true

#prometheus
management:
  server:
    port: 8092
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  enabled: true
  exclude-api-paths: /v3/api-docs.yaml,/swagger-ui,/actuator,/error,/v2,/swagger,/webjars
  ignore-check: true
  header-name: X-JWT-Assertion